
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gamal Rashad
 */
public class Byanat3omala extends javax.swing.JFrame {

    /**
     * Creates new form Byanat3omala
*/
    
    
    public Byanat3omala() {
        initComponents();
        con=Connect.connect();
Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
Default();
    }
Connection con = null;    
     PreparedStatement preparedStatement = null;
     ResultSet resultSet = null;
      ResultSetMetaData rsmeta;
    String date ;
    int id;
    
    
    void Default() {

        try {

//txtShumberNum.setText("0");
txtName2.setText("");

            String sql = "SELECT * FROM `sales` ";
            preparedStatement = con.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            String sql1 = " SELECT id as`الكود`,name as `الإسم `,rtdsph,rtdcyl,rtdaxis,rtrsph,rtrcyl,rtraxis,ltrsph,ltrcyl,ltraxis,ltdsph,ltdaxis,ltdcyl,jpdd,jpdr  FROM `sales` ";
            PreparedStatement preparedStatement1 = con.prepareStatement(sql1);
            ResultSet rs = preparedStatement1.executeQuery();
            if (resultSet.next()) {
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Here : " + e.getMessage());
            e.printStackTrace();
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtLt_DAxis = new javax.swing.JTextField();
        txtLt_RAxis = new javax.swing.JTextField();
        txtLt_DCyl = new javax.swing.JTextField();
        txtLt_RCyl = new javax.swing.JTextField();
        txtRtDAxis = new javax.swing.JTextField();
        txtRtRAxis = new javax.swing.JTextField();
        txtRtDCyl = new javax.swing.JTextField();
        txtRtDSph = new javax.swing.JTextField();
        txtRtRCyl = new javax.swing.JTextField();
        txtLt_RSph = new javax.swing.JTextField();
        txtLt_DSph = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        txtRtRSph = new javax.swing.JTextField();
        txtJPDD = new javax.swing.JTextField();
        txtJPDR = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("بيانات العملاء");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(237, 234, 234));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(105, 105, 105));
        jLabel10.setText("إسم العميل");

        txtName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtName2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtName2KeyReleased(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Actions-window-close-icon.png"))); // NOI18N
        jButton5.setText("رجوع");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        jScrollPane1.setBackground(new java.awt.Color(66, 192, 251));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "الكود", "الإسم"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBackground(new java.awt.Color(237, 234, 234));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(105, 105, 105));
        jLabel29.setText("D");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(105, 105, 105));
        jLabel30.setText("R");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(105, 105, 105));
        jLabel31.setText("Rt ");

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(105, 105, 105));
        jLabel32.setText("Lt");

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(105, 105, 105));
        jLabel33.setText("Sph");

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(105, 105, 105));
        jLabel34.setText("Axis");

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(105, 105, 105));
        jLabel35.setText("Cyl.");

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(105, 105, 105));
        jLabel36.setText("Sph");

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(105, 105, 105));
        jLabel37.setText("Cyl.");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(105, 105, 105));
        jLabel38.setText("JPD");

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(105, 105, 105));
        jLabel39.setText("Axis");

        txtLt_DAxis.setEditable(false);
        txtLt_DAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtLt_DAxis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLt_DAxis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLt_DAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLt_DAxisKeyTyped(evt);
            }
        });

        txtLt_RAxis.setEditable(false);
        txtLt_RAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtLt_RAxis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLt_RAxis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLt_RAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLt_RAxisKeyTyped(evt);
            }
        });

        txtLt_DCyl.setEditable(false);
        txtLt_DCyl.setBackground(new java.awt.Color(255, 255, 255));
        txtLt_DCyl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLt_DCyl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLt_DCyl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLt_DCylKeyTyped(evt);
            }
        });

        txtLt_RCyl.setEditable(false);
        txtLt_RCyl.setBackground(new java.awt.Color(255, 255, 255));
        txtLt_RCyl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLt_RCyl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLt_RCyl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLt_RCylKeyTyped(evt);
            }
        });

        txtRtDAxis.setEditable(false);
        txtRtDAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtRtDAxis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRtDAxis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRtDAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRtDAxisKeyTyped(evt);
            }
        });

        txtRtRAxis.setEditable(false);
        txtRtRAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtRtRAxis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRtRAxis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRtRAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRtRAxisKeyTyped(evt);
            }
        });

        txtRtDCyl.setEditable(false);
        txtRtDCyl.setBackground(new java.awt.Color(255, 255, 255));
        txtRtDCyl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRtDCyl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRtDCyl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRtDCylActionPerformed(evt);
            }
        });
        txtRtDCyl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRtDCylKeyTyped(evt);
            }
        });

        txtRtDSph.setEditable(false);
        txtRtDSph.setBackground(new java.awt.Color(255, 255, 255));
        txtRtDSph.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRtDSph.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRtDSph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRtDSphKeyTyped(evt);
            }
        });

        txtRtRCyl.setEditable(false);
        txtRtRCyl.setBackground(new java.awt.Color(255, 255, 255));
        txtRtRCyl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRtRCyl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRtRCyl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRtRCylKeyTyped(evt);
            }
        });

        txtLt_RSph.setEditable(false);
        txtLt_RSph.setBackground(new java.awt.Color(255, 255, 255));
        txtLt_RSph.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLt_RSph.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLt_RSph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLt_RSphKeyTyped(evt);
            }
        });

        txtLt_DSph.setEditable(false);
        txtLt_DSph.setBackground(new java.awt.Color(255, 255, 255));
        txtLt_DSph.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLt_DSph.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLt_DSph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLt_DSphActionPerformed(evt);
            }
        });
        txtLt_DSph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLt_DSphKeyTyped(evt);
            }
        });

        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtRtRSph.setEditable(false);
        txtRtRSph.setBackground(new java.awt.Color(255, 255, 255));
        txtRtRSph.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRtRSph.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRtRSph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRtRSphKeyTyped(evt);
            }
        });

        txtJPDD.setEditable(false);
        txtJPDD.setBackground(new java.awt.Color(255, 255, 255));
        txtJPDD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJPDD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJPDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJPDDKeyTyped(evt);
            }
        });

        txtJPDR.setEditable(false);
        txtJPDR.setBackground(new java.awt.Color(255, 255, 255));
        txtJPDR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJPDR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJPDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJPDRActionPerformed(evt);
            }
        });
        txtJPDR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJPDRKeyTyped(evt);
            }
        });

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(txtRtRSph, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtRtRCyl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRtRAxis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel33)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel35)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel34)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(txtRtDSph, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtRtDCyl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRtDAxis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLt_DSph, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtLt_RSph))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLt_DCyl, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtLt_RCyl))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLt_RAxis, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtLt_DAxis))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtJPDR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtJPDD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel38)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel36)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel37)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel39))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel32)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(11, 11, 11))
                    .addComponent(jLabel31))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel33))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJPDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLt_DSph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLt_DCyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLt_DAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(txtRtDSph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRtDCyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRtDAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRtRSph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30)
                                    .addComponent(txtRtRCyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRtRAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLt_RSph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLt_RCyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtJPDR)
                                .addComponent(txtLt_RAxis)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtName2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName2KeyReleased
        //        search();

        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        con = Connect.connect();
        int r  = jTable1.getSelectedRow();
        String n = jTable1.getModel().getValueAt(r, 0).toString();
        try{
            String sql = "Select * from sales where id = '"+ n +"'";
            preparedStatement = con.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            while (resultSet.next()){

                id = resultSet.getInt("id");

                String name = resultSet.getString("name");
                
                txtName2.setText(name);

                   double RDSPH = resultSet.getDouble("rtdsph");
               txtRtDSph.setText(Double.toString(RDSPH));
               
               double RDCYL= resultSet.getDouble("rtdcyl");
               txtRtDCyl.setText(Double.toString(RDCYL));
               
               double RDAXIS = resultSet.getDouble("rtdaxis");
               txtRtDAxis.setText(Double.toString(RDAXIS));
               
               double RRSPH = resultSet.getDouble("rtrsph");
               txtRtRSph.setText(Double.toString(RRSPH));
               
               double RRCYL = resultSet.getDouble("rtrcyl");
               txtRtRCyl.setText(Double.toString(RRCYL));
               
               double RRAXIS = resultSet.getDouble("rtraxis");
               txtRtRAxis.setText(Double.toString(RRAXIS));
               
               double LDSPH = resultSet.getDouble("ltdsph");
               txtLt_DSph.setText(Double.toString(LDSPH));
               
               double LDCYL = resultSet.getDouble("ltdcyl");
               txtLt_DCyl.setText(Double.toString(LDCYL));
               
                double LDAXIS = resultSet.getDouble("ltdaxis");
               txtLt_DAxis.setText(Double.toString(LDAXIS));
               
                double LRSPH = resultSet.getDouble("ltrsph");
               txtLt_RSph.setText(Double.toString(LRSPH));
               
               double LRCYL = resultSet.getDouble("ltrcyl");
               txtLt_RCyl.setText(Double.toString(LRCYL));
               
               double LRAXIS = resultSet.getDouble("ltraxis");
               txtLt_RAxis.setText(Double.toString(LRAXIS));
               
               double JPDD = resultSet.getDouble("jpdd");
               txtJPDD.setText(Double.toString(JPDD));
               
               double JPDR = resultSet.getDouble("jpdr");
               txtJPDR.setText(Double.toString(JPDR));

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

       
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtLt_DAxisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLt_DAxisKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_DAxisKeyTyped

    private void txtLt_RAxisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLt_RAxisKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_RAxisKeyTyped

    private void txtLt_DCylKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLt_DCylKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_DCylKeyTyped

    private void txtLt_RCylKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLt_RCylKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_RCylKeyTyped

    private void txtRtDAxisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtDAxisKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtDAxisKeyTyped

    private void txtRtRAxisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtRAxisKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtRAxisKeyTyped

    private void txtRtDCylActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRtDCylActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtDCylActionPerformed

    private void txtRtDCylKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtDCylKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtDCylKeyTyped

    private void txtRtDSphKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtDSphKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtDSphKeyTyped

    private void txtRtRCylKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtRCylKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtRCylKeyTyped

    private void txtLt_RSphKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLt_RSphKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_RSphKeyTyped

    private void txtLt_DSphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLt_DSphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_DSphActionPerformed

    private void txtLt_DSphKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLt_DSphKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLt_DSphKeyTyped

    private void txtRtRSphKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtRSphKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtRSphKeyTyped

    private void txtJPDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJPDDKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtJPDDKeyTyped

    private void txtJPDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJPDRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJPDRActionPerformed

    private void txtJPDRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJPDRKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_txtJPDRKeyTyped

    private void txtName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName2KeyPressed
  // TODO add your handling code here:
       
          try{
         con = Connect.connect();
              String sql = "select * from  sales where name like '" + txtName2.getText() + "%'";
            preparedStatement = con.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();


          
            
         jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
            /*
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            jTable1e.getColumnModel().getColumn(sale).setCellRenderer(rightRenderer);

            jTable1e  .getColumnModel().getColumn(1).setCellRenderer(rightRenderer);

            */
            
 
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment((int) JLabel.CENTER_ALIGNMENT);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        for (int x = 0; x < jTable1.getColumnCount(); x++) {
            jTable1.getColumnModel().getColumn(x).setCellRenderer(centerRenderer);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Byanat3omala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Byanat3omala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Byanat3omala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Byanat3omala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Byanat3omala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtJPDD;
    private javax.swing.JTextField txtJPDR;
    private javax.swing.JTextField txtLt_DAxis;
    private javax.swing.JTextField txtLt_DCyl;
    private javax.swing.JTextField txtLt_DSph;
    private javax.swing.JTextField txtLt_RAxis;
    private javax.swing.JTextField txtLt_RCyl;
    private javax.swing.JTextField txtLt_RSph;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtRtDAxis;
    private javax.swing.JTextField txtRtDCyl;
    private javax.swing.JTextField txtRtDSph;
    private javax.swing.JTextField txtRtRAxis;
    private javax.swing.JTextField txtRtRCyl;
    private javax.swing.JTextField txtRtRSph;
    // End of variables declaration//GEN-END:variables

}
