
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gamal Rashad
 */
public class DailyGard extends javax.swing.JFrame {

    /**
     * Creates new form DailyGard
     */
    public DailyGard() {
        initComponents();
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setSize(1100, 750);
        this.setResizable(false);
    }
    
    Connection con = null;    
     PreparedStatement pst = null;
     ResultSet rs = null;
     //Sales
     int Total_Sold ,mosta7k,erad;
     //warsha
     int total_Warsha,mosta7k_warsha,erad_warsha;
     
     
     //Maktab 3adasat
     int total_3adsat ,payed_3adsat,doyon_3adast;
     
              //Trader
             int total_Trade ,payed_Trade,doyon_trade;
                     int total_masrof;
                             
                     
                     int b,mab;
              int mas;
      ResultSetMetaData rsmeta;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total_mabe3at = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_warsha = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtErad_warsha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMosta7a2_warsha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotal_Warsha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtName4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtName5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_togar = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_maktab3adsat = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_masrofat = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTotal_3adsat = new javax.swing.JTextField();
        txtPaed_3adasat = new javax.swing.JTextField();
        txtDoyon_3adasat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTotal_Trade = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPaed_Trade = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDoyon_Trade = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        total_mabe3at7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtTotaal = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtTotalPayed = new javax.swing.JTextField();
        txtTotal1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtTotalDoyon = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtTotalMosta7a2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("جرد يومي");

        jPanel1.setBackground(new java.awt.Color(237, 234, 234));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(105, 105, 105));
        jLabel9.setText("تاريخ اليوم");

        txtName1.setEditable(false);
        txtName1.setBackground(new java.awt.Color(204, 204, 255));
        txtName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtName1KeyReleased(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Apps-accessories-calculator-icon.png"))); // NOI18N
        jButton5.setText("عرض");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jButton5))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(237, 234, 234));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "الإسم", "رقم الشمبر", "رقم العدسه", "الإجمالي", "المدفوع", "الباقي"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(105, 105, 105));
        jLabel16.setText("المبيعات");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(105, 105, 105));
        jLabel8.setText("إجمالى المبيعات");

        total_mabe3at.setEditable(false);
        total_mabe3at.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total_mabe3at.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_mabe3at.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                total_mabe3atKeyReleased(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        table_warsha.setBackground(new java.awt.Color(204, 204, 255));
        table_warsha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_warsha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "إسم المحل", "التاريخ", "إجمالي", "مدفوع", "باقي"
            }
        ));
        jScrollPane2.setViewportView(table_warsha);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(105, 105, 105));
        jLabel17.setText("حساب الورشة");

        txtErad_warsha.setEditable(false);
        txtErad_warsha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtErad_warsha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtErad_warsha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtErad_warshaKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(105, 105, 105));
        jLabel10.setText("صافي إيراد الورشه");

        txtMosta7a2_warsha.setEditable(false);
        txtMosta7a2_warsha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMosta7a2_warsha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMosta7a2_warsha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMosta7a2_warshaKeyReleased(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(105, 105, 105));
        jLabel11.setText("إجمالي مستحقات الورشه");

        txtTotal_Warsha.setEditable(false);
        txtTotal_Warsha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal_Warsha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal_Warsha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotal_WarshaActionPerformed(evt);
            }
        });
        txtTotal_Warsha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotal_WarshaKeyReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(105, 105, 105));
        jLabel12.setText("إجمالي إيراد الورشه");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 105));
        jLabel13.setText("إجمالى المستحقات");

        txtName4.setEditable(false);
        txtName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtName4KeyReleased(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 105, 105));
        jLabel14.setText("صافي الإيراد");

        txtName5.setEditable(false);
        txtName5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtName5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(406, 406, 406)
                                .addComponent(jLabel16))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtName5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total_mabe3at, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMosta7a2_warsha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal_Warsha)
                            .addComponent(txtErad_warsha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtTotal_Warsha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMosta7a2_warsha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(total_mabe3at, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtErad_warsha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel5.setBackground(new java.awt.Color(237, 234, 234));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(105, 105, 105));
        jLabel19.setText("التجار");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(105, 105, 105));
        jLabel18.setText("مصروفات");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(105, 105, 105));
        jLabel20.setText("مكتب العدسات");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table_togar.setBackground(new java.awt.Color(204, 204, 255));
        table_togar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_togar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "إسم التاجر", "التاريخ", "إجمالي", "مدفوع", "باقي"
            }
        ));
        jScrollPane3.setViewportView(table_togar);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        table_maktab3adsat.setBackground(new java.awt.Color(204, 204, 255));
        table_maktab3adsat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_maktab3adsat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "مكتب العدسات", "التاريخ", "الإجمالي", "المدفوع", "الباقي"
            }
        ));
        jScrollPane4.setViewportView(table_maktab3adsat);

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        table_masrofat.setBackground(new java.awt.Color(204, 204, 255));
        table_masrofat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_masrofat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "المصروفات", "القيمة", "التاريخ"
            }
        ));
        jScrollPane5.setViewportView(table_masrofat);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(105, 105, 105));
        jLabel21.setText("إجمالي سعرالعدسات");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(105, 105, 105));
        jLabel23.setText("إجمالي الديون");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(105, 105, 105));
        jLabel22.setText("إجمالي المدفوع");

        txtTotal_3adsat.setEditable(false);
        txtTotal_3adsat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal_3adsat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal_3adsat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotal_3adsatKeyReleased(evt);
            }
        });

        txtPaed_3adasat.setEditable(false);
        txtPaed_3adasat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPaed_3adasat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaed_3adasat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaed_3adasatKeyReleased(evt);
            }
        });

        txtDoyon_3adasat.setEditable(false);
        txtDoyon_3adasat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDoyon_3adasat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDoyon_3adasat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDoyon_3adasatKeyReleased(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(105, 105, 105));
        jLabel24.setText("إجمالي سعر الشنابر");

        txtTotal_Trade.setEditable(false);
        txtTotal_Trade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal_Trade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal_Trade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotal_TradeKeyReleased(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(105, 105, 105));
        jLabel25.setText("إجمالي المدفوع");

        txtPaed_Trade.setEditable(false);
        txtPaed_Trade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPaed_Trade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaed_Trade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaed_TradeKeyReleased(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(105, 105, 105));
        jLabel26.setText("إجمالي الديون");

        txtDoyon_Trade.setEditable(false);
        txtDoyon_Trade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDoyon_Trade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDoyon_Trade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDoyon_TradeKeyReleased(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(105, 105, 105));
        jLabel27.setText("إجمالي  المصروفات");

        total_mabe3at7.setEditable(false);
        total_mabe3at7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total_mabe3at7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_mabe3at7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                total_mabe3at7KeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(105, 105, 105));
        jLabel31.setText("إجمالى الإيراد");

        txtTotaal.setEditable(false);
        txtTotaal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotaal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotaal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotaalKeyReleased(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(105, 105, 105));
        jLabel32.setText("إجمالى المصروفات");

        txtTotalPayed.setEditable(false);
        txtTotalPayed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalPayed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPayed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPayedKeyTyped(evt);
            }
        });

        txtTotal1.setEditable(false);
        txtTotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotal1KeyTyped(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(105, 105, 105));
        jLabel33.setText("صافي الربح ");

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(105, 105, 105));
        jLabel34.setText("إجمالى الديون");

        txtTotalDoyon.setEditable(false);
        txtTotalDoyon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalDoyon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalDoyon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalDoyonKeyTyped(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(105, 105, 105));
        jLabel35.setText("إجمالى المستحقات");

        txtTotalMosta7a2.setEditable(false);
        txtTotalMosta7a2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalMosta7a2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalMosta7a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalMosta7a2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalMosta7a2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDoyon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalPayed, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)
                        .addComponent(txtTotalPayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(txtTotalDoyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34)
                        .addComponent(txtTotalMosta7a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtDoyon_3adasat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPaed_3adasat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal_3adsat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21))
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtDoyon_Trade)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPaed_Trade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal_Trade, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24))
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(total_mabe3at7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtDoyon_3adasat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(txtPaed_3adasat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotal_3adsat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotal_Trade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(txtPaed_Trade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtDoyon_Trade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_mabe3at7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1KeyReleased

    private void total_mabe3atKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_mabe3atKeyReleased
        //        search();

        // TODO add your handling code here:
    }//GEN-LAST:event_total_mabe3atKeyReleased

    private void txtErad_warshaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErad_warshaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErad_warshaKeyReleased

    private void txtMosta7a2_warshaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMosta7a2_warshaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMosta7a2_warshaKeyReleased

    private void txtTotal_WarshaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotal_WarshaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal_WarshaActionPerformed

    private void txtTotal_WarshaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotal_WarshaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal_WarshaKeyReleased

    private void txtName4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName4KeyReleased

    private void txtName5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName5KeyReleased

    private void txtTotal_3adsatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotal_3adsatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal_3adsatKeyReleased

    private void txtPaed_3adasatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaed_3adasatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaed_3adasatKeyReleased

    private void txtDoyon_3adasatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoyon_3adasatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoyon_3adasatKeyReleased

    private void txtTotal_TradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotal_TradeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal_TradeKeyReleased

    private void txtPaed_TradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaed_TradeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaed_TradeKeyReleased

    private void txtDoyon_TradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoyon_TradeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoyon_TradeKeyReleased

    private void total_mabe3at7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_mabe3at7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_total_mabe3at7KeyReleased

    private void txtTotaalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotaalKeyReleased
        //        search();

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotaalKeyReleased

    private void txtTotalPayedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPayedKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPayedKeyTyped

    private void txtTotal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotal1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal1KeyTyped

    private void txtTotalDoyonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalDoyonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDoyonKeyTyped

    private void txtTotalMosta7a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalMosta7a2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMosta7a2KeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // TODO add your handling code here:

        DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        Calendar cal = Calendar.getInstance();
        txtName1.setText(dateFormat.format(cal.getTime()));
        //        String date1 =((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
        //        String date2 =((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        //        if(date1.equals("")||date2.equals("")){
            //             JOptionPane.showMessageDialog(this, "من فضلك تاكد من التاريخ");
            //        }

        //Sum Of Total Sold
        double maksab=0;

        try{
            con=Connect.connect();
            String sql ="Select SUM(total) ,SUM(payed) ,SUM(reset) FROM sales  where date ='"+txtName1.getText()+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            Total_Sold=( rs.getInt(1));
            erad=( rs.getInt(2));
            mosta7k=rs.getInt(3);
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //Total  Warsha
        try{
            String sql ="Select SUM(total) , SUM(payed),SUM(reset) FROM warsha  where date ='"+txtName1.getText()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            total_Warsha=( rs.getInt(1));
            erad_warsha=( rs.getInt(2));
            mosta7k_warsha=( rs.getInt(3));

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        // ----------------------------- Maksab

        //        maksab=Total_Sold+total_Warsha;
        //        total_mabe3at.setText(maksab+"");
        //---------------------------------------

        //اجمالي المصروفات

        try{
            con=Connect.connect();
            String sql ="Select SUM(total) ,SUM(payed),SUM(reset) FROM glass_office  where date ='"+txtName1.getText()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            total_3adsat=( rs.getInt(1));
            payed_3adsat=( rs.getInt(2));
            doyon_3adast=( rs.getInt(3));

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        try{
            String sql ="Select SUM(total),SUM(payed),SUM(reset) FROM traders_1  where date ='"+txtName1.getText()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            total_Trade=( rs.getInt(1));
            payed_Trade=( rs.getInt(2));
            doyon_trade=( rs.getInt(3));

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        try{
            con=Connect.connect();
            String sql ="Select SUM(value) FROM masrofat  where date ='"+txtName1.getText()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            total_masrof=( rs.getInt(1));

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //All From Sales Table
        total_mabe3at.setText(Total_Sold+"");
        txtName4.setText(mosta7k+"");
        txtName5.setText(erad+"");

        //All From Warsha Table
        txtTotal_Warsha.setText(total_Warsha+"");
        txtMosta7a2_warsha.setText(mosta7k_warsha+"");
        txtErad_warsha.setText(erad_warsha+"");

        //All From Glasses Office Table
        txtTotal_3adsat.setText(total_3adsat+"");
        txtDoyon_3adasat.setText(doyon_3adast+"");
        txtPaed_3adasat.setText(payed_3adsat+"");

        //All From Trader_1 Office Table
        txtTotal_Trade.setText(total_Trade+"");
        txtDoyon_Trade.setText(doyon_trade+"");
        txtPaed_Trade.setText(payed_Trade+"");

        //All From Masrofat Table
        total_mabe3at7.setText(total_masrof+"");

        int totaal=Total_Sold+total_Warsha;
        txtTotaal.setText(totaal+"");

        int totalPayed=payed_3adsat+payed_Trade+total_masrof;
        txtTotalPayed.setText(totalPayed+"");

        int totalDoyon=doyon_3adast+doyon_trade;
        txtTotalDoyon.setText(totalDoyon+"");

        int totaMosta7a2=mosta7k_warsha+mosta7k;
        txtTotalMosta7a2.setText(totaMosta7a2+"");

        int safyReb7=(totaal)-(total_Trade+total_3adsat+total_masrof);
        txtTotal1.setText(safyReb7+"");
        //        mas=total_3adsat+e+total_masrof;
        //
        //        txtTotal.setText(mas+"");
        //
        //        int t=Total_Sold-mas;
        //        txtTotal1.setText(t+"");

        //عرض فى جدول المبيعات
        try{
            con=Connect.connect();
            String sql ="Select name,num_shamp,num_lens,total,payed,reset FROM sales  where date ='"+txtName1.getText()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            Vector<String> colName = new Vector<String>();

            colName.add("الاسم");
            colName.add("رقم الشمبر");
            colName.add("رقم العدسة");
            colName.add("الاجمالي");
            colName.add("المدفوع");
            colName.add("الباقي");

            Vector<Vector> rows = new Vector<Vector>();

            rsmeta = rs.getMetaData();
            for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                // colName.add(rsmeta.getColumnName(i));

            }
            while (rs.next()) {
                Vector<String> oneRow = new Vector<String>();
                for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                    oneRow.add(rs.getString(i));

                }
                rows.add(oneRow);
            }

            DefaultTableModel tableModel = new DefaultTableModel(rows, colName);
            jTable1.setModel(tableModel);

            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(78);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(65);

            jTable1.setShowHorizontalLines(true);
            jTable1.setShowVerticalLines(true);
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //--------------------Warsha

        //عرض فى جدول الورشه
        try{
            con=Connect.connect();
            String sql ="Select shop_name,date,total,payed,reset FROM warsha  where date ='"+txtName1.getText()+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            Vector<String> colName = new Vector<String>();

            colName.add("إسم المحل");
            colName.add("التاريخ ");
            colName.add("الاجمالي");
            colName.add("المدفوع");
            colName.add("الباقي");

            Vector<Vector> rows = new Vector<Vector>();

            rsmeta = rs.getMetaData();
            for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                // colName.add(rsmeta.getColumnName(i));

            }
            while (rs.next()) {
                Vector<String> oneRow = new Vector<String>();
                for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                    oneRow.add(rs.getString(i));

                }
                rows.add(oneRow);
            }

            DefaultTableModel tableModel = new DefaultTableModel(rows, colName);
            table_warsha.setModel(tableModel);

            table_warsha.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            table_warsha.getColumnModel().getColumn(0).setPreferredWidth(90);
            table_warsha.getColumnModel().getColumn(1).setPreferredWidth(90);

            table_warsha.setShowHorizontalLines(true);
            table_warsha.setShowVerticalLines(true);
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        // عرض فى  جدول مكتب العدسات

        try{
            con=Connect.connect();
            String sql ="Select office,date,total,payed,reset FROM glass_office  where date ='"+txtName1.getText()+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            Vector<String> colName = new Vector<String>();

            colName.add("إسم المكتب");
            colName.add("التاريخ ");
            colName.add("الاجمالي");
            colName.add("المدفوع");
            colName.add("الباقي");

            Vector<Vector> rows = new Vector<Vector>();

            rsmeta = rs.getMetaData();
            for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                // colName.add(rsmeta.getColumnName(i));

            }
            while (rs.next()) {
                Vector<String> oneRow = new Vector<String>();
                for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                    oneRow.add(rs.getString(i));

                }
                rows.add(oneRow);
            }

            DefaultTableModel tableModel = new DefaultTableModel(rows, colName);
            table_maktab3adsat.setModel(tableModel);

            table_maktab3adsat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            table_maktab3adsat.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_maktab3adsat.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_maktab3adsat.getColumnModel().getColumn(2).setPreferredWidth(100);

            table_maktab3adsat.setShowHorizontalLines(true);
            table_maktab3adsat.setShowVerticalLines(true);
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //عرض فى جدول التجار
        try{
            con=Connect.connect();
            String sql ="Select t_name,date,total,payed,reset FROM traders_1  where date ='"+txtName1.getText()+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            Vector<String> colName = new Vector<String>();

            colName.add("إسم التاجر");
            colName.add("التاريخ ");
            colName.add("الاجمالي");
            colName.add("المدفوع");
            colName.add("الباقي");

            Vector<Vector> rows = new Vector<Vector>();

            rsmeta = rs.getMetaData();
            for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                // colName.add(rsmeta.getColumnName(i));

            }
            while (rs.next()) {
                Vector<String> oneRow = new Vector<String>();
                for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                    oneRow.add(rs.getString(i));

                }
                rows.add(oneRow);
            }

            DefaultTableModel tableModel = new DefaultTableModel(rows, colName);
            table_togar.setModel(tableModel);

            table_togar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            table_togar.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_togar.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_togar.getColumnModel().getColumn(2).setPreferredWidth(100);

            table_togar.setShowHorizontalLines(true);
            table_togar.setShowVerticalLines(true);
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //عرض فى جدول المصروفات
        try{
            con=Connect.connect();
            String sql ="Select masaryInfo,value,date FROM masrofat  where date ='"+txtName1.getText()+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            Vector<String> colName = new Vector<String>();

            colName.add("المصروفات");
            colName.add("القيمه ");
            colName.add("التاريخ");

            Vector<Vector> rows = new Vector<Vector>();

            rsmeta = rs.getMetaData();
            for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                // colName.add(rsmeta.getColumnName(i));

            }
            while (rs.next()) {
                Vector<String> oneRow = new Vector<String>();
                for (int i = 1; i <= rsmeta.getColumnCount(); i++) {
                    oneRow.add(rs.getString(i));

                }
                rows.add(oneRow);
            }

            DefaultTableModel tableModel = new DefaultTableModel(rows, colName);
            table_masrofat.setModel(tableModel);

            table_masrofat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            table_masrofat.getColumnModel().getColumn(0).setPreferredWidth(300);
            table_masrofat.getColumnModel().getColumn(1).setPreferredWidth(300);
            table_masrofat.getColumnModel().getColumn(2).setPreferredWidth(300);

            table_masrofat.setShowHorizontalLines(true);
            table_masrofat.setShowVerticalLines(true);
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyGard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyGard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyGard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyGard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyGard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table_maktab3adsat;
    private javax.swing.JTable table_masrofat;
    private javax.swing.JTable table_togar;
    private javax.swing.JTable table_warsha;
    private javax.swing.JTextField total_mabe3at;
    private javax.swing.JTextField total_mabe3at7;
    private javax.swing.JTextField txtDoyon_3adasat;
    private javax.swing.JTextField txtDoyon_Trade;
    private javax.swing.JTextField txtErad_warsha;
    private javax.swing.JTextField txtMosta7a2_warsha;
    protected javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName4;
    private javax.swing.JTextField txtName5;
    private javax.swing.JTextField txtPaed_3adasat;
    private javax.swing.JTextField txtPaed_Trade;
    private javax.swing.JTextField txtTotaal;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JTextField txtTotalDoyon;
    private javax.swing.JTextField txtTotalMosta7a2;
    private javax.swing.JTextField txtTotalPayed;
    private javax.swing.JTextField txtTotal_3adsat;
    private javax.swing.JTextField txtTotal_Trade;
    private javax.swing.JTextField txtTotal_Warsha;
    // End of variables declaration//GEN-END:variables
}
